// Generated by internal/cmd/arm-in/generate.go.  DO NOT EDIT!

// +build !waginterp

package in

const (
	Bc = CondImm19(0x54000000)

	FCMP = DiscardRegRegType(0x1e202000)

	BRK = Imm16(0xd4200000)

	B  = Imm26(0x14000000)
	BL = Imm26(0x94000000)

	BR  = Reg(0xd61f0000)
	BLR = Reg(0xd63f0000)
	RET = Reg(0xd65f0000)

	TBZ  = RegImm14Bit(0x36000000)
	TBNZ = RegImm14Bit(0x37000000)

	MOVN = RegImm16HwSf(0x12800000)
	MOVZ = RegImm16HwSf(0x52800000)
	MOVK = RegImm16HwSf(0x72800000)

	ADR = RegImm19Imm2(0x10000000)

	CBZ  = RegImm19Size(0x34000000)
	CBNZ = RegImm19Size(0x35000000)

	CSEL  = RegRegCondRegSf(0x1a800000)
	CSINC = RegRegCondRegSf(0x1a800400)

	FCSEL = RegRegCondRegType(0x1e200c00)

	ADDi  = RegRegImm12ShiftSf(0x11000000)
	ADDSi = RegRegImm12ShiftSf(0x31000000)
	SUBi  = RegRegImm12ShiftSf(0x51000000)
	SUBSi = RegRegImm12ShiftSf(0x71000000)

	STR = RegRegImm12Size(0xb9000000)
	LDR = RegRegImm12Size(0xb9400000)

	ADDe  = RegRegImm3ExtRegSf(0x0b200000)
	SUBSe = RegRegImm3ExtRegSf(0x6b200000)

	UBFM = RegRegImm6Imm6NSf(0x53000000)

	ADDs  = RegRegImm6RegShiftSf(0x0b000000)
	SUBs  = RegRegImm6RegShiftSf(0x4b000000)
	SUBSs = RegRegImm6RegShiftSf(0x6b000000)
	ANDs  = RegRegImm6RegShiftSf(0x0a000000)
	ORRs  = RegRegImm6RegShiftSf(0x2a000000)
	ANDSs = RegRegImm6RegShiftSf(0x6a000000)

	LDRpost = RegRegImm9Size(0xb8400400)
	STRpre  = RegRegImm9Size(0xb8000c00)
	STUR    = RegRegImm9Size(0xb8000000)
	LDUR    = RegRegImm9Size(0xb8400000)

	MADD = RegRegRegRegSf(0x1b000000)
	MSUB = RegRegRegRegSf(0x1b008000)

	RORV = RegRegRegSf(0x1ac02c00)
	UDIV = RegRegRegSf(0x1ac00800)
	SDIV = RegRegRegSf(0x1ac00c00)

	LDRr = RegRegSOptionRegSize(0xb8600800)

	RBIT = RegRegSf(0x5ac00000)
	CLZ  = RegRegSf(0x5ac01000)

	FMOV = RegRegType(0x1e204000)
	FNEG = RegRegType(0x1e214000)

	FMOVtog   = RegRegTypeSf(0x1e260000)
	FMOVfromg = RegRegTypeSf(0x1e270000)
)
